### ISSUE TITLE
serverless support with aws fargate 

### ISSUE THREAD

**Issue by pahud** [aws-samples/nexus-oss-on-aws#13]
Amazon EKS just announced its latest support for EFS on Faragate on Aug 17. Does this project support this now?

New – AWS Fargate for Amazon EKS now supports Amazon EFS
https://aws.amazon.com/tw/blogs/aws/new-aws-fargate-for-amazon-eks-now-supports-amazon-efs/

### Other

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by zxkane** [comment]
I will have a look at it and update the findings.
