### ISSUE TITLE
install ALB ingress controller via Helm chart maintained by EKS

### ISSUE THREAD

**Issue by zxkane** [aws-samples/nexus-oss-on-aws#18]
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1271#issuecomment-694539132

### Other

* [ ] :wave: I may be able to implement this feature request

---

This is a :rocket: Feature Request

**Comment by pahud** [comment]
How about https://www.npmjs.com/package/cdk8s-aws-alb-ingress-controller by @guan840912  ?

**Comment by zxkane** [comment]
Pahud, thanks for your propose. Will evaluate the library.
